export const defaultHTMLTemplate = {
  name: "Default HTML Template",
  description: "Default HTML report template",
  type: "html",
  category: "default",
  metadata: {
    version: "1.0"
  },
  sections: [
    {
      id: "header",
      title: "Case Report",
      content: `
        <h1>{{case.name}}</h1>
        <ul class="info-list">
          <li><strong>Case Number:</strong> {{case.id}}</li>
          <li><strong>Date Generated:</strong> {{currentDate}}</li>
          <li><strong>Status:</strong> {{case.status}}</li>
        </ul>
      `
    },
    {
      id: "case_details", 
      title: "Case Details",
      content: `
        <h2>Case Information</h2>
        <ul class="info-list">
          <li><strong>Case Type:</strong> {{case.caseType}}</li>
          <li><strong>Priority:</strong> {{case.casePriority}}</li>
          <li><strong>Status:</strong> {{case.status}}</li>
          <li><strong>Date Opened:</strong> {{case.caseDate}}</li>
          {{#if options.caseSummary.includeMyInfo}}
            <li><strong>Case Examiner:</strong> {{case.caseExaminer}}</li>
            <li><strong>Case Investigator:</strong> {{case.caseInvestigator}}</li>
            <li><strong>Organization:</strong> {{organization.name}}</li>
          {{/if}}
        </ul>

        {{#if options.caseSummary.includeCaseDescription}}
          <h3>Description</h3>
          <div>{{case.description}}</div>
        {{/if}}

        {{#if options.caseSummary.customSummary}}
          <h3>Custom Summary</h3>
          <div>{{options.caseSummary.customSummary}}</div>
        {{/if}}
      `
    },
    {
      id: "evidence",
      title: "Evidence",
      content: `
        {{#if options.evidence.enabled}}
          <h2>Evidence Items</h2>
          {{#each case.evidence}}
            <div class="evidence-item">
              <h3>{{this.name}}</h3>
              <ul class="info-list">
                <li><strong>Type:</strong> {{this.type.name}}</li>
                {{#if ../options.evidence.includeMetadata}}
                  <li><strong>Size:</strong> {{this.size}}</li>
                  <li><strong>Created:</strong> {{this.createdAt}}</li>
                  <li><strong>Location:</strong> {{this.evidenceLocation.name}}</li>
                {{/if}}
                {{#if ../options.evidence.includeHashes}}
                  <li><strong>MD5:</strong> {{this.id}}</li>
                {{/if}}
              </ul>
              {{#if ../options.evidence.includeChainOfCustody}}
                <div class="chain-of-custody">
                  <h4>Chain of Custody</h4>
                  {{#each this.chainOfCustody}}
                    <div>{{this.createdAt}} - {{this.user.name}}: {{this.action}}</div>
                  {{/each}}
                </div>
              {{/if}}
            </div>
          {{/each}}
        {{/if}}
      `
    },
    {
      id: "evidence_gallery",
      title: "Evidence Gallery", 
      content: `
        {{#if options.evidence.enabled}}
          <h2>Evidence Gallery</h2>
          <div class="evidence-gallery">
            {{#each case.evidence}}
              {{#if (eq type.name "Image")}}
                <div class="gallery-item">
                  <img src="{{this.filePath}}" alt="{{this.name}}" />
                  <p class="caption">{{this.name}}</p>
                </div>
              {{/if}}
            {{/each}}
          </div>
        {{/if}}
      `
    },
    {
      id: "activities", 
      title: "Activities",
      content: `
        {{#if options.activities.enabled}}
          <h2>Case Activities</h2>
          {{#each case.activities}}
            {{#if (or (not this.private) ../options.activities.includePrivate)}}
              <div class="activity">
                <strong>{{this.createdAt}}</strong> - {{this.user.name}}: {{this.description}}
              </div>
            {{/if}}
          {{/each}}
        {{/if}}
      `
    },
    {
      id: "notes",
      title: "Notes",
      content: `
        {{#if options.notes.enabled}}
          <h2>Case Notes</h2>
          {{#each case.notes}}
            {{#if (or (not this.private) ../options.notes.includePrivate)}}
              <div class="note">
                <h3>{{this.title}}</h3>
                <div class="note-meta">
                  Added by {{this.user.name}} on {{this.createdAt}}
                </div>
                <div class="note-content">
                  {{this.content}}
                </div>
              </div>
            {{/if}}
          {{/each}}
        {{/if}}
      `
    },
    {
      id: "signature",
      title: "Signature",
      content: `
        {{#if options.signature.enabled}}
          <div class="signature-section">
            <h2>Report Authentication</h2>
            <p>This report was generated by {{user.name}} on {{currentDate}}</p>
            
            {{#if options.signature.typedSignature}}
              <div class="typed-signature">
                <p class="signature-text">{{options.signature.typedSignature}}</p>
              </div>
            {{/if}}

            {{#if options.signature.includeTitle}}
              <p class="examiner-title">{{user.title}}</p>
            {{/if}}

            {{#if options.signature.includeOrganization}}
              <p class="organization">{{organization.name}}</p>
            {{/if}}

            {{#if options.signature.includeContact}}
              <div class="contact-info">
                <p>Contact: {{user.email}}</p>
                {{#if organization.phone}}<p>Phone: {{organization.phone}}</p>{{/if}}
              </div>
            {{/if}}
          </div>
        {{/if}}
      `
    }
  ]
}

const defaultCSS = `
  @font-face {
    font-family: 'Helvetica';
    src: url('/fonts/Helvetica.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'Helvetica';
    src: url('/fonts/Helvetica-Bold.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
  }

  @font-face {
    font-family: 'Helvetica';
    src: url('/fonts/Helvetica-Oblique.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
  }

  @font-face {
    font-family: 'Helvetica';
    src: url('/fonts/Helvetica-BoldOblique.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
  }

  @import url('https://fonts.googleapis.com/css2?family=Whisper&display=swap');
  
  body {
    font-family: 'Helvetica', sans-serif;
    line-height: 1.6;
    color: #333;
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
  }
  
  h1, h2, h3 {
    font-family: 'Helvetica', sans-serif;
    font-weight: bold;
    color: #2c3e50;
    margin-top: 1.5em;
  }
  
  .info-list {
    list-style: none;
    padding: 0;
  }
  
  .info-list li {
    margin-bottom: 0.5em;
  }
  
  .evidence-item, .activity, .note {
    border: 1px solid #ddd;
    padding: 15px;
    margin-bottom: 15px;
    border-radius: 4px;
  }
  
  .chain-of-custody {
    margin-top: 10px;
    padding: 10px;
    background: #f8f9fa;
  }
  
  .signature-section {
    margin-top: 50px;
    padding-top: 20px;
    border-top: 2px solid #ddd;
  }
  
  .typed-signature {
    margin: 30px 0;
  }
  
  .signature-text {
    font-family: 'Whisper', cursive;
    font-size: 36px;
    color: #000;
    border-bottom: 1px solid #000;
    display: inline-block;
    padding: 0 20px 5px;
  }
  
  .examiner-title {
    font-weight: bold;
    margin: 10px 0 5px;
  }
  
  .organization {
    color: #666;
    margin-bottom: 10px;
  }
  
  .contact-info {
    font-size: 0.9em;
    color: #666;
    margin-top: 15px;
  }
`;