export const defaultHTMLTemplate = {
  name: "Default HTML Template",
  description: "Default HTML report template",
  type: "html",
  category: "default",
  metadata: {
    version: "1.0"
  },
  sections: [
    {
      id: "header",
      title: "Case Report",
      content: `
        <h1>{{case.name}}</h1>
        <ul class="info-list">
          <li><strong>Case Number:</strong> {{case.id}}</li>
          <li><strong>Date Generated:</strong> {{currentDate}}</li>
          <li><strong>Status:</strong> {{case.status}}</li>
        </ul>
      `
    },
    {
      id: "case_details", 
      title: "Case Details",
      content: `
        <h2>Case Information</h2>
        <ul class="info-list">
          <li><strong>Case Type:</strong> {{case.caseType}}</li>
          <li><strong>Priority:</strong> {{case.casePriority}}</li>
          <li><strong>Status:</strong> {{case.status}}</li>
          <li><strong>Date Opened:</strong> {{case.caseDate}}</li>
          {{#if options.caseSummary.includeMyInfo}}
            <li><strong>Case Examiner:</strong> {{case.caseExaminer}}</li>
            <li><strong>Case Investigator:</strong> {{case.caseInvestigator}}</li>
            <li><strong>Organization:</strong> {{organization.name}}</li>
          {{/if}}
        </ul>

        {{#if options.caseSummary.includeCaseDescription}}
          <h3>Description</h3>
          <div>{{case.description}}</div>
        {{/if}}

        {{#if options.caseSummary.customSummary}}
          <h3>Custom Summary</h3>
          <div>{{options.caseSummary.customSummary}}</div>
        {{/if}}
      `
    },
    {
      id: "evidence",
      title: "Evidence",
      content: `
        {{#if options.evidence.enabled}}
          <h2>Evidence Items</h2>
          {{#each case.evidence}}
            <div class="evidence-item">
              <h3>{{this.name}}</h3>
              <ul class="info-list">
                <li><strong>Type:</strong> {{this.type.name}}</li>
                {{#if ../options.evidence.includeMetadata}}
                  <li><strong>Size:</strong> {{this.size}}</li>
                  <li><strong>Created:</strong> {{this.createdAt}}</li>
                  <li><strong>Location:</strong> {{this.evidenceLocation.name}}</li>
                {{/if}}
                {{#if ../options.evidence.includeHashes}}
                  <li><strong>MD5:</strong> {{this.id}}</li>
                {{/if}}
              </ul>
              {{#if ../options.evidence.includeChainOfCustody}}
                <div class="chain-of-custody">
                  <h4>Chain of Custody</h4>
                  {{#each this.chainOfCustody}}
                    <div>{{this.createdAt}} - {{this.user.name}}: {{this.action}}</div>
                  {{/each}}
                </div>
              {{/if}}
            </div>
          {{/each}}
        {{/if}}
      `
    },
    {
      id: "evidence_gallery",
      title: "Evidence Gallery", 
      content: `
        {{#if options.evidence.enabled}}
          <h2>Evidence Gallery</h2>
          <div class="evidence-gallery">
            {{#each case.evidence}}
              {{#if (eq type.name "Image")}}
                <div class="gallery-item">
                  <img src="graphics/{{name}}" alt="{{name}}" />
                  <p class="caption">{{name}}</p>
                </div>
              {{/if}}
            {{/each}}
          </div>
        {{/if}}
      `
    },
    {
      id: "activities", 
      title: "Activities",
      content: `
        {{#if options.activities.enabled}}
          <h2>Case Activities</h2>
          {{#each case.activities}}
            {{#if (or (not this.private) ../options.activities.includePrivate)}}
              <div class="activity">
                <strong>{{this.createdAt}}</strong> - {{this.user.name}}: {{this.description}}
              </div>
            {{/if}}
          {{/each}}
        {{/if}}
      `
    },
    {
      id: "notes",
      title: "Notes",
      content: `
        {{#if options.notes.enabled}}
          <h2>Case Notes</h2>
          {{#each case.notes}}
            {{#if (or (not this.private) ../options.notes.includePrivate)}}
              <div class="note">
                <h3>{{this.title}}</h3>
                <div class="note-meta">
                  Added by {{this.user.name}} on {{this.createdAt}}
                </div>
                <div class="note-content">
                  {{this.content}}
                </div>
              </div>
            {{/if}}
          {{/each}}
        {{/if}}
      `
    },
    {
      id: "signature",
      title: "Signature",
      content: `
        {{#if options.signature.enabled}}
          <div class="signature-section">
            <h2>Report Authentication</h2>
            <p>This report was generated by {{user.name}} on {{currentDate}}</p>
            
            {{#if options.signature.typedSignature}}
              <div class="typed-signature">
                <p class="signature-text">{{options.signature.typedSignature}}</p>
              </div>
            {{/if}}

            {{#if options.signature.includeTitle}}
              <p class="examiner-title">{{user.title}}</p>
            {{/if}}

            {{#if options.signature.includeOrganization}}
              <p class="organization">{{organization.name}}</p>
            {{/if}}

            {{#if options.signature.includeContact}}
              <div class="contact-info">
                <p>Contact: {{user.email}}</p>
                {{#if organization.phone}}<p>Phone: {{organization.phone}}</p>{{/if}}
              </div>
            {{/if}}
          </div>
        {{/if}}
      `
    }
  ]
};
